### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by cyx0118** [wtcpython/WinUIEdge#4]
生成开始于 21:30...
1>------ 已启动生成: 项目: Edge, 配置: Debug x64 ------
1>D:\code\.net\WinUIEdge-main\Settings\DownloadItem.xaml.cs(14,13,14,31): error CS0103: 当前上下文中不存在名称“DownloadFolderCard”
1>D:\code\.net\WinUIEdge-main\Settings\DownloadItem.xaml.cs(45,17,45,35): error CS0103: 当前上下文中不存在名称“DownloadFolderCard”
1>D:\code\.net\WinUIEdge-main\Settings\StartItem.xaml.cs(27,35,27,49): error CS0103: 当前上下文中不存在名称“backgroundCard”
1>D:\code\.net\WinUIEdge-main\Settings\StartItem.xaml.cs(57,46,57,60): error CS0103: 当前上下文中不存在名称“backgroundCard”
1>已完成生成项目“Edge.csproj”的操作 - 失败。
========== 生成: 0 成功，1 失败，0 最新，0 已跳过 ==========
========== 生成 于 21:30 完成，耗时 00.478 秒 ==========
========== “部署”: 0 成功，0 失败，0已跳过 ==========
========== 部署 于 21:30 完成，耗时 00.478 秒 ==========

**Comment by wtcpython** [comment]
在xaml 中要把 `Name` 换成 `x:Name` ，不过我自己一直写都没发现问题，刚才自己拉取了源码一次，报了相同的问题，改了之后应该没问题了

**Comment by cyx0118** [comment]
ok啊，大佬！

**Comment by cyx0118** [comment]
我试试

**Comment by wtcpython** [comment]
我已经将修改后的代码推送到 `main` 分支上，现在应该不会有问题了。如果不行，你也可以重新再拉取一下修改后的代码试一试。

**Comment by cyx0118** [comment]
好的

**Comment by cyx0118** [comment]
怎么了嘛？






                       
原始邮件
                       
                     

发件人："wtc"< ***@***.*** &gt;;

发件时间：2024/4/5 12:47

收件人："wtcpython/WinUIEdge"< ***@***.*** &gt;;

抄送人："cyx0118"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [wtcpython/WinUIEdge] 构建失败 (Issue #4)




 
Closed #4 as completed.

**Comment by wtcpython** [comment]
就是把这个 Issue 关了，没什么事。
收到邮箱应该是 Github 会发邮件告诉你这件事。

Closed [#4](https://github.com/wtcpython/WinUIEdge/issues/4) as completed.

这句话就是说这个 Issue 已关闭
