### ISSUE TITLE
设置界面调整

### ISSUE THREAD

**Issue by Gaoyifei1011** [wtcpython/WinUIEdge#8]
1.隐私和安全
基本，严格和防护中的信息介绍，对应的 ListView 的 SelectionMode 属性值应该为 None，而不是默认值 Single
![image](https://github.com/wtcpython/WinUIEdge/assets/49179966/0b640a49-a1dd-431f-827e-e22e5d208575)

2.下载更改文件夹时，如果浏览器处于提权模式下点击更改按钮，调用 FolderPicker 会出现异常，建议请尝试使用 try catch 捕捉一下
![image](https://github.com/wtcpython/WinUIEdge/assets/49179966/33a5a7d0-cfce-4c3c-8352-7a9c6f0b3923)
![image](https://github.com/wtcpython/WinUIEdge/assets/49179966/0b7a5826-643f-45b1-8d90-c7223f998c38)

3.设置页面的标签页内容乱码
![image](https://github.com/wtcpython/WinUIEdge/assets/49179966/9bdfedf9-3870-4a16-b00e-cddc2486cdc8)

期待您的项目发展的越来越好
真诚祝愿，怡飞

**Comment by wtcpython** [comment]
感谢你提供的修改建议！我将很快修复这些问题。
