### ISSUE TITLE
自定义右键菜单的功能改进建议

### ISSUE THREAD

**Issue by Gaoyifei1011** [wtcpython/WinUIEdge#9]
我在您的 Github 历史提交记录中寻找到您曾经尝试过自定义窗口右键菜单，但是因为某种原因失败而告终。https://github.com/wtcpython/WinUIEdge/commit/d04661ce7b0129be201b92347fd3b4ed511fb577
我在这里提供一下我目前寻找到可行的一个解决方案，这也是在我的项目中正在使用到的。

![image](https://github.com/wtcpython/WinUIEdge/assets/49179966/dc319360-88f8-4eb0-9450-120a50b467f5)

这是我自定义标题栏右键菜单的菜单浮出控件的内容
https://github.com/Gaoyifei1011/GetStoreApp/blob/main/GetStoreApp/Views/Windows/MainWindow.xaml#L72

使用自定义窗口标题栏时，这时 Window.ExtendsContentIntoTitlebar = true，需要做出下面所列出的操作。
https://github.com/Gaoyifei1011/GetStoreApp/blob/main/GetStoreApp/Views/Windows/MainWindow.xaml.cs#L169
寻找非工作区（窗口类：InputNonClientPointerSource 类）的窗口句柄，并为其添加窗口过程。

处理非工作区窗口消息，尤其是默认窗口右键菜单的消息（WM_NCRBUTTONUP）
https://github.com/Gaoyifei1011/GetStoreApp/blob/991978b158ea4235b053721dc98c413775b8cfc3/GetStoreApp/Views/Windows/MainWindow.xaml.cs#L939

处理应用窗口处于焦点状态时，键盘按下 Alt + Space 的窗口消息
为应用窗口句柄添加窗口过程，处理相应的窗口消息
https://github.com/Gaoyifei1011/GetStoreApp/blob/991978b158ea4235b053721dc98c413775b8cfc3/GetStoreApp/Views/Windows/MainWindow.xaml.cs#L165
https://github.com/Gaoyifei1011/GetStoreApp/blob/991978b158ea4235b053721dc98c413775b8cfc3/GetStoreApp/Views/Windows/MainWindow.xaml.cs#L910

我使用的自定义的窗口右键菜单浮出控件的样式（您可以自己定制所需要外观的窗口右键菜单）
https://github.com/Gaoyifei1011/GetStoreApp/blob/main/GetStoreApp/Styles/MenuFlyout.xaml

期待您的项目发展的越来越好
真诚祝愿，怡飞

**Comment by wtcpython** [comment]
感谢你的帮助，我一直以来试图解决自定义右键菜单的问题，但总是无法得到解决，您提供的帮助帮我解决了大麻烦！

**Comment by wtcpython** [comment]
https://github.com/wtcpython/WinUIEdge/assets/119155053/21870209-18f6-4d70-94b4-29ab7eac111f

想问以下这里的右键菜单能否和窗口菜单一样可以自定义，如果我定义了窗口菜单的内容能否同步到这里。

**Comment by Gaoyifei1011** [comment]
> 2024-05-19.114222.mp4 
> 想问以下这里的右键菜单能否和窗口菜单一样可以自定义，如果我定义了窗口菜单的内容能否同步到这里。

可以，这里需要处理一下一个未公开的消息，需要在主窗口过程中添加对0x0313消息的处理。
